/**
 * Fetches review data from the review platform's public page and writes
 * src/reviews.data.js with the current rating, count, and label.
 *
 * Uses Playwright (already a devDependency) to render the JS-heavy page,
 * then extracts rating data from JSON-LD.
 *
 * On failure, warns and preserves the existing file (cache/fallback).
 */

import { writeFileSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { chromium } from '@playwright/test';
import { getPlatformUrl } from '../src/reviews.platform.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT = resolve(__dirname, '..', 'src', 'reviews.data.js');

const TARGET_URL = getPlatformUrl();

// ---------------------------------------------------------------------------
// Label computation
// ---------------------------------------------------------------------------

function computeLabel(rating) {
  const r = parseFloat(rating);
  if (r >= 4.5) return 'Excellent';
  if (r >= 3.5) return 'Great';
  if (r >= 2.5) return 'Average';
  if (r >= 1.5) return 'Poor';
  return 'Bad';
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  console.log('Fetching review data...');

  let browser;
  try {
    browser = await chromium.launch();
    const page = await browser.newPage();
    await page.goto(TARGET_URL, { waitUntil: 'domcontentloaded', timeout: 30000 });

    // Wait for JSON-LD to appear in the rendered DOM
    await page.waitForSelector('script[type="application/ld+json"]', {
      state: 'attached',
      timeout: 10000,
    });

    // Extract all JSON-LD blocks from the rendered page
    const jsonLdBlocks = await page.evaluate(() => {
      const scripts = document.querySelectorAll('script[type="application/ld+json"]');
      return Array.from(scripts).map((s) => s.textContent);
    });

    let rating = null;
    let count = null;

    // Recursively search for aggregateRating in JSON-LD (may be nested in @graph arrays)
    function findAggregate(obj) {
      if (rating) return; // already found
      if (obj === null || obj === undefined || typeof obj !== 'object') return;
      if (obj.aggregateRating) {
        rating = String(obj.aggregateRating.ratingValue);
        count = String(obj.aggregateRating.reviewCount);
        return;
      }
      for (const v of Object.values(obj)) {
        if (Array.isArray(v)) {
          v.forEach((item) => findAggregate(item));
        } else if (typeof v === 'object' && v !== null) {
          findAggregate(v);
        }
      }
    }

    for (const block of jsonLdBlocks) {
      try {
        findAggregate(JSON.parse(block));
        if (rating) break;
      } catch {
        // Skip malformed JSON-LD
      }
    }

    if (!rating || !count) {
      console.warn('  WARNING: Could not parse rating data from page.');
      if (existsSync(OUTPUT)) {
        console.warn('  Using existing cached data.');
      }
      return;
    }

    const label = computeLabel(rating);

    const content = [
      '// Auto-generated by scripts/fetch-reviews.js — do not edit manually',
      `// Last fetched: ${new Date().toISOString()}`,
      '',
      `export const reviewRating = ${JSON.stringify(rating)};`,
      `export const reviewCount = ${JSON.stringify(count)};`,
      `export const reviewLabel = ${JSON.stringify(label)};`,
      '',
    ].join('\n');

    writeFileSync(OUTPUT, content);
    console.log(`  Updated src/reviews.data.js: rating=${rating}, count=${count}, label=${label}`);
  } catch (err) {
    console.warn(`  WARNING: Could not fetch review data: ${err.message}`);
    if (existsSync(OUTPUT)) {
      console.warn('  Using existing cached data.');
    } else {
      console.warn('  No cached data available — build will use seed values.');
    }
  } finally {
    if (browser) await browser.close();
  }
}

main();
