// Auto-generated by scripts/fetch-reviews.js — do not edit manually
// Last fetched: 2026-06-04T20:18:21.151Z

export const reviewRating = '4.3';
export const reviewCount = '101';
export const reviewLabel = 'Great';
