// Auto-generated by scripts/fetch-reviews.js — do not edit manually
// Last fetched: 2026-06-05T03:07:37.852Z

export const reviewRating = '4.3';
export const reviewCount = '101';
export const reviewLabel = 'Great';
