// Auto-generated by scripts/fetch-reviews.js — do not edit manually
// Last fetched: 2026-03-13T18:04:00.142Z

export const reviewRating = '4.3';
export const reviewCount = '95';
export const reviewLabel = 'Great';
